### ISSUE TITLE
Angular 18  "No provider for _MatSelect!" issue

### ISSUE THREAD

**Issue by AliJaghel** [bithost-gmbh/ngx-mat-select-search#471]
after upgrading to angular 18, getting this error:

NullInjectorError: NullInjectorError: No provider for _MatSelect!
    at NullInjector.get (core.mjs:1660:27)
    at R3Injector.get (core.mjs:3106:33)
    at R3Injector.get (core.mjs:3106:33)
    at R3Injector.get (core.mjs:3106:33)
    at ChainedInjector.get (core.mjs:5448:36)
    at lookupTokenUsingModuleInjector (core.mjs:5801:39)
    at getOrCreateInjectable (core.mjs:5849:12)
    at ɵɵdirectiveInject (core.mjs:11395:19)
    at NodeInjectorFactory.MatSelectSearchComponent_Factory [as factory] (ngx-mat-select-search.mjs:617:49)
    at getNodeInjectable (core.mjs:6061:44)

**Comment by SarathSri3233** [comment]
@AliJaghel  how to fix this issue?
