### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SarathSri3233** [bithost-gmbh/ngx-mat-select-search#472]
console.js:36 ERROR 
Error: Uncaught (in promise): NullInjectorError: R3InjectorError(SubscriberModule)[MatSelect -> MatSelect -> MatSelect]: 
  NullInjectorError: No provider for MatSelect!
NullInjectorError: NullInjectorError: No provider for MatSelect!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at ChainedInjector.get (core.mjs:14018:36)
    at lookupTokenUsingModuleInjector (core.mjs:4608:39)
    at getOrCreateInjectable (core.mjs:4656:12)
    at Module.ɵɵdirectiveInject (core.mjs:11801:19)
    at NodeInjectorFactory.MatSelectSearchComponent_Factory [as factory] (ngx-mat-select-search.mjs:39:115)
    at getNodeInjectable (core.mjs:4862:44)
    at instantiateAllDirectives (core.mjs:12629:27)
    at createDirectivesInstances (core.mjs:12045:5)
    at ɵɵelementStart (core.mjs:16336:9)
    at Module.ɵɵelement (core.mjs:16394:5)

Angular CLI: 16.2.14
Node: 18.10.0
Package Manager: npm 8.19.2
OS: linux x64

"ngx-mat-select-search": "^7.0.1",

 - OS: Ubuntu 22.04
 - Browser: chrome

**Comment by macjohnny** [comment]
@SarathSri3233 can you please add more information about your template, the controller, the package.json, the actual angular&ngx-mat-select-search versions used?

**Comment by SarathSri3233** [comment]
@macjohnny  

Package.json
`"dependencies": {
    "@angular/animations": "^16.2.12",
    "@angular/cdk": "^16.2.14",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^16.2.12",
    "@angular/localize": "^16.2.12",
    "@angular/material": "^16.2.14",
    "@angular/material-moment-adapter": "^16.2.14",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@aws-amplify/auth": "^3.2.6",
    "@babel/compat-data": "^7.8.0",
    "ngx-mat-select-search": "^7.0.1",
    "rxjs": "~6.6.7",
    "stream": "0.0.2",
    "tslib": "^2.0.0",
    "xlsx": "^0.15.5",
    "xng-breadcrumb": "^9.0.0",
    "zone.js": "~0.13.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.14",
    "@angular/cli": "^16.2.14",
    "@angular/compiler-cli": "^16.2.12",
    "@angular/language-service": "^16.2.12",
    "@types/jest": "^29.5.11",
    "@types/node": "^18.19.3",
    "codelyzer": "^6.0.2",
    "jest": "^29.7.0",
    "jest-preset-angular": "^13.1.1",
    "protractor": "~7.0.0",
    "ts-node": "^10.9.2",
    "tslint": "~6.1.0",
    "typescript": "~4.9.5"
  }`

Template:

<mat-form-field appearance="outline">
                <mat-label>Select Examiner</mat-label>
                <mat-select [formControl]="examiner" (selectionChange)="examinerSelect($event.value)">
                    <mat-option>
                        <ngx-mat-select-search [formControl]="examinerFilterCtrl"
                                            placeholderLabel="Find Examiner" i18n-placeholderLabel
                                            noEntriesFoundLabel="No Matching Examiner Found"
                                            i18n-noEntriesFoundLabel>
                        </ngx-mat-select-search>
                    </mat-option>
                    <mat-option *ngFor="let examiner of filteredExaminerList | async" [value]="examiner.id">
                        {{examiner?.name}}
                    </mat-option>
                </mat-select>
            </mat-form-field>

ngx-mat-select-search versions:   "ngx-mat-select-search": "^7.0.1",

**Comment by SarathSri3233** [comment]
Hi @macjohnny 

Template:
![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/59691210/5533d9ac-e744-4891-b336-d0a0164dc33b)

 package.json:
![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/59691210/eef3b60f-4fce-4ff9-aeb8-561b614bff05)

Angular CLI: 16.2.14
"ngx-mat-select-search": "^7.0.1",

This issue occurred after updating from Angular 15 to Angular 16. It was working fine in Angular 15.

**Comment by macjohnny** [comment]
what is the exact version of ngx-mat-select-search you are using?

are you using the MatLegacySelectModule or the MatSelectModule?

**Comment by SarathSri3233** [comment]
I'm using MatLegacySelectModule

ngx-mat-select-search : 7.0.1

**Comment by macjohnny** [comment]
the legacy module is not supported on ngx-mat-select-search 7+, see https://github.com/bithost-gmbh/ngx-mat-select-search/tree/master?tab=readme-ov-file#compatibility. Please use v6
